export class DbGlobalStatusDescription {
    Description = {
        Aborted_clients: `The number of connections that were aborted because the client died without closing the connection properly. `,
        Aborted_connects: `The number of failed attempts to connect to the MySQL server.`,
        Binlog_cache_disk_use: `The number of transactions that used the temporary binary log cache `,
        Binlog_cache_use: `The number of transactions that used the binary log cache.`,
        Binlog_stmt_cache_disk_use: `The number of nontransaction statements that used the binary log statement cache.`,
        Binlog_stmt_cache_use: `The number of nontransactional statements that used the binary log statement cache.`,
        Bytes_received: `The number of bytes received from all clients.`,
        Bytes_sent: `The number of bytes sent to all clients.`,
        Com_xxx: `The Com_xxx statement counter variables indicate the number of times each xxx statement has been executed.`,
        Com_delete: `indicate the number of times each deleted statement has been executed.`,
        Com_update: `indicate the number of times each updated statement has been executed.`,
        Com_stmt_prepare: ``,
        Com_stmt_execute: ``,
        Com_stmt_fetch: `stands for the total number of network round - trips issued when fetching from cursors.`,
        Com_stmt_send_long_data: ``,
        Com_stmt_reset: ``,
        Com_stmt_close: ``,
        Com_stmt_reprepare: `indicates the number of times statements were automatically reprepared by the server.`,
        Com_explain_other: `indicates the number of EXPLAIN FOR CONNECTION statements executed.`,
        Com_change_repl_filter: `indicates the number of CHANGE REPLICATION FILTER statements executed.`,
        Connection_errors_xxx: `These variables provide information about errors that occur during the client connection process.`,
        Connection_errors_accept: `The number of errors that occurred during calls to accept() on the listening port.`,
        Connection_errors_internal: `The number of connections refused due to internal errors in the server.`,
        Connection_errors_max_connections: `The number of connections refused because the server max_connections limit was reached.`,
        Connection_errors_peer_address: `The number of errors that occurred while searching for connecting client IP addresses.`,
        Connection_errors_select: `The number of errors that occurred during calls to select() or poll() on the listening port.`,
        Connection_errors_tcpwrap: `The number of connections refused by the libwrap library.`,
        Connections: `The number of connection attempts(successful or not) to the MySQL server.`,
        Created_tmp_disk_tables: `The number of internal on - disk temporary tables created by the server while executing statements.`,
        Created_tmp_files: `How many temporary files mysqld has created.`,
        Created_tmp_tables: `The number of internal temporary tables created by the server while executing statements.`,
        Delayed_errors: `This status variable is deprecated`,
        Delayed_insert_threads: `This status variable is deprecated`,
        Delayed_writes: `This status variable is deprecated`,
        Flush_commands: `The number of times the server flushes tables`,
        group_replication_primary_member: `Shows the primary member's UUID when the group is operating in single-primary mode.`,
        Handler_commit: `The number of internal COMMIT statements.`,
        Handler_delete: `The number of times that rows have been deleted from tables.`,
        Handler_external_lock: `The server increments this variable for each call to its external_lock() function`,
        Handler_mrr_init: `The number of times the server uses a storage engine's own Multi-Range.`,
        Handler_prepare: `A counter for the prepare phase of two - phase commit operations.`,
        Handler_read_first: `The number of times the first entry in an index was read..`,
        Handler_read_key: `The number of requests to read a row based on a key.`,
        Handler_read_last: `The number of requests to read the last key in an index.`,
        Handler_read_next: `The number of requests to read the next row in key order.`,
        Handler_read_prev: `The number of requests to read the previous row in key order.`,
        Handler_read_rnd: `The number of requests to read a row based on a fixed position.`,
        Handler_read_rnd_next: `The number of requests to read the next row in the data file.`,
        Handler_rollback: `The number of requests for a storage engine to perform a rollback operation.`,
        Handler_savepoint: `The number of requests for a storage engine to place a savepoint.`,
        Handler_savepoint_rollback: `The number of requests for a storage engine to roll back to a savepoint.`,
        Handler_update: `The number of requests to update a row in a table.`,
        Handler_write: `The number of requests to insert a row in a table.`,
        Innodb_available_undo_logs: `The Innodb_available_undo_logs status variable is deprecated`,
        Innodb_buffer_pool_dump_status: `The progress of an operation to record the pages held in the InnoDB buffer pool`,
        Innodb_buffer_pool_load_status: `The progress of an operation to warm up the InnoDB buffer pool by reading in a set of pages`,
        Innodb_buffer_pool_bytes_data: `The total number of bytes in the InnoDB buffer pool containing data.`,
        Innodb_buffer_pool_pages_data: `The number of pages in the InnoDB buffer pool containing data.`,
        Innodb_buffer_pool_bytes_dirty: `The total current number of bytes held in dirty pages in the InnoDB buffer pool.`,
        Innodb_buffer_pool_pages_dirty: `The current number of dirty pages in the InnoDB buffer pool.`,
        Innodb_buffer_pool_pages_flushed: `The number of requests to flush pages from the InnoDB buffer pool.`,
        Innodb_buffer_pool_pages_free: `The number of free pages in the InnoDB buffer pool.`,
        Innodb_buffer_pool_pages_latched: `The number of latched pages in the InnoDB buffer pool.`,
        Innodb_buffer_pool_pages_misc: `The number of pages in the InnoDB buffer pool that are busy because they have been allocated for administrative overhead.`,
        Innodb_buffer_pool_pages_total: `The total size of the InnoDB buffer pool, in pages.`,
        Innodb_buffer_pool_read_ahead: `The number of pages read into the InnoDB buffer pool by the read - ahead background thread.`,
        Innodb_buffer_pool_read_ahead_evicted: `The number of pages read into the InnoDB buffer pool by the read - ahead background thread that were subsequently evicted without having been accessed by queries.`,
        Innodb_buffer_pool_read_ahead_rnd: `The number of “random” read - aheads initiated by InnoDB.`,
        Innodb_buffer_pool_read_requests: `The number of logical read requests.`,
        Innodb_buffer_pool_reads: `The number of logical reads that InnoDB could not satisfy from the buffer pool, and had to read directly from disk.`,
        Innodb_buffer_pool_resize_status: `The status of an operation to resize the InnoDB buffer pool dynamically.`,
        Innodb_buffer_pool_wait_free: `Normally, writes to the InnoDB buffer pool happen in the background.`,
        Innodb_buffer_pool_write_requests: `The number of writes done to the InnoDB buffer pool.`,
        Innodb_data_fsyncs: `The number of fsync() operations.`,
        Innodb_data_pending_fsyncs: `The current number of pending fsync() operations.`,
        Innodb_data_pending_reads: `The current number of pending reads.`,
        Innodb_data_pending_writes: `The current number of pending writes.`,
        Innodb_data_read: `The amount of data read since the server was started(in bytes).`,
        Innodb_data_reads: `The total number of data reads(OS file reads).`,
        Innodb_data_writes: `The total number of data writes.`,
        Innodb_data_written: `The amount of data written so far, in bytes.`,
        Innodb_dblwr_pages_written: `The number of pages that have been written to the doublewrite buffer.See Section 14.12.1, “InnoDB Disk I / O”.`,
        Innodb_dblwr_writes: `The number of doublewrite operations that have been performed.See Section 14.12.1, “InnoDB Disk I / O”.`,
        Innodb_have_atomic_builtins: `Indicates whether the server was built with atomic instructions.`,
        Innodb_log_waits: `The number of times that the log buffer was too small and a wait was required for it to be flushed before continuing.`,
        Innodb_log_write_requests: `The number of write requests for the InnoDB redo log.`,
        Innodb_log_writes: `The number of physical writes to the InnoDB redo log file.`,
        Innodb_num_open_files: `The number of files InnoDB currently holds open.`,
        Innodb_os_log_fsyncs: `The number of fsync() writes done to the InnoDB redo log files.`,
        Innodb_os_log_pending_fsyncs: `The number of pending fsync() operations for the InnoDB redo log files.`,
        Innodb_os_log_pending_writes: `The number of pending writes to the InnoDB redo log files.`,
        Innodb_os_log_written: `The number of bytes written to the InnoDB redo log files.`,
        Innodb_page_size: `InnoDB page size(default 16KB).`,
        Innodb_pages_created: `The number of pages created by operations on InnoDB tables.`,
        Innodb_pages_read: `The number of pages read from the InnoDB buffer pool by operations on InnoDB tables.`,
        Innodb_pages_written: `The number of pages written by operations on InnoDB tables.`,
        Innodb_row_lock_current_waits: `The number of row locks currently being waited for by operations on InnoDB tables.`,
        Innodb_row_lock_time: `The total time spent in acquiring row locks for InnoDB tables, in milliseconds.`,
        Innodb_row_lock_time_avg: `The average time to acquire a row lock for InnoDB tables, in milliseconds.`,
        Innodb_row_lock_time_max: `The maximum time to acquire a row lock for InnoDB tables, in milliseconds.`,
        Innodb_row_lock_waits: `The number of times operations on InnoDB tables had to wait for a row lock.`,
        Innodb_rows_deleted: `The number of rows deleted from InnoDB tables.`,
        Innodb_rows_inserted: `The number of rows inserted into InnoDB tables.`,
        Innodb_rows_read: `The number of rows read from InnoDB tables.`,
        Innodb_rows_updated: `The number of rows updated in InnoDB tables.`,
        Innodb_truncated_status_writes: `The number of times output from the SHOW ENGINE INNODB STATUS statement has been truncated.`,
        Key_blocks_not_flushed: `The number of key blocks in the MyISAM key cache that have changed but have not yet been flushed to disk.`,
        Key_blocks_unused: `The number of unused blocks in the MyISAM key cache.`,
        Key_blocks_used: `The number of used blocks in the MyISAM key cache.`,
        Key_read_requests: `The number of requests to read a key block from the MyISAM key cache.`,
        Key_reads: `The number of physical reads of a key block from disk into the MyISAM key cache.`,
        Key_write_requests: `The number of requests to write a key block to the MyISAM key cache.`,
        Key_writes: `The number of physical writes of a key block from the MyISAM key cache to disk.`,
        Last_query_cost: `The total cost of the last compiled query as computed by the query optimizer.`,
        Last_query_partial_plans: `The number of iterations the query optimizer made in execution plan construction for the previous query.`,
        Locked_connects: `The number of attempts to connect to locked user accounts.`,
        Max_execution_time_exceeded: `The number of SELECT statements for which the execution timeout was exceeded.`,
        Max_execution_time_set: `The number of SELECT statements for which a nonzero execution timeout was set.`,
        Max_execution_time_set_failed: `The number of SELECT statements for which the attempt to set an execution timeout failed.`,
        Max_used_connections: `The maximum number of connections that have been in use simultaneously since the server started.`,
        Max_used_connections_time: `The time at which Max_used_connections reached its current value.`,
        Not_flushed_delayed_rows: `This status variable is deprecated`,
        mecab_charset: `The character set currently used by the MeCab full - text parser plugin.`,
        Ongoing_anonymous_transaction_count: `Shows the number of ongoing transactions which have been marked as anonymous.`,
        Ongoing_anonymous_gtid_violating_transaction_count: `This status variable is only available in debug builds.`,
        Ongoing_automatic_gtid_violating_transaction_count: `This status variable is only available in debug builds.`,
        Open_files: `The number of files that are open.This count includes regular files opened by the server.`,
        Open_streams: `The number of streams that are open.`,
        Open_table_definitions: `The number of cached.frm files.`,
        Open_tables: `The number of tables that are open.`,
        Opened_files: `The number of files that have been opened with my_open().`,
        Opened_table_definitions: `The number of.frm files that have been cached.`,
        Opened_tables: `The number of tables that have been opened.`,
        Performance_schema_xxx: `Performance Schema status variables are listed ”.`,
        Prepared_stmt_count: `The current number of prepared statements. `,
        Qcache_free_blocks: `The number of free memory blocks in the query cache.`,
        Qcache_free_memory: `The amount of free memory for the query cache.`,
        Qcache_hits: `The number of query cache hits.`,
        Qcache_inserts: `The number of queries added to the query cache.`,
        Qcache_lowmem_prunes: `The number of queries that were deleted from the query cache because of low memory.`,
        Qcache_not_cached: `The number of noncached queries.`,
        Qcache_queries_in_cache: `The number of queries registered in the query cache.`,
        Qcache_total_blocks: `The total number of blocks in the query cache.`,
        Queries: `The number of statements executed by the server.This variable includes statements executed within stored programs, unlike the Questions variable.`,
        Questions: `The number of statements executed by the server.This includes only statements executed within stored programs, unlike the Queries variable.`,
        Rpl_semi_sync_master_clients: `The number of semisynchronous replicas.`,
        Rpl_semi_sync_master_net_avg_wait_time: `The average time in microseconds the source waited for a replica reply.`,
        Rpl_semi_sync_master_net_wait_time: `The total time in microseconds the source waited for replica replies.`,
        Rpl_semi_sync_master_net_waits: `The total number of times the source waited for replica replies.`,
        Rpl_semi_sync_master_no_times: `The number of times the source turned off semisynchronous replication.`,
        Rpl_semi_sync_master_no_tx: `The number of commits that were not acknowledged successfully by a replica.`,
        Rpl_semi_sync_master_status: `Whether semisynchronous replication currently is operational on the source.`,
        Rpl_semi_sync_master_timefunc_failures: `The number of times the source failed when calling time functions such as gettimeofday().`,
        Rpl_semi_sync_master_tx_avg_wait_time: `The average time in microseconds the source waited for each transaction.`,
        Rpl_semi_sync_master_tx_wait_time: `The total time in microseconds the source waited for transactions.`,
        Rpl_semi_sync_master_tx_waits: `The total number of times the source waited for transactions.`,
        Rpl_semi_sync_master_wait_pos_backtraverse: `The total number of times the source waited for an event with binary coordinates.`,
        Rpl_semi_sync_master_wait_sessions: `The number of sessions currently waiting for replica replies.`,
        Rpl_semi_sync_master_yes_tx: `The number of commits that were acknowledged successfully by a replica.`,
        Rpl_semi_sync_slave_status: `Whether semisynchronous replication currently is operational on the replica.`,
        Rsa_public_key: `Its value is the public key used by the sha256_password authentication plugin for RSA key pair - based password exchange.`,
        Select_full_join: `The number of joins that perform table scans because they do not use indexes.`,
        Select_full_range_join: `The number of joins that used a range search on a reference table.`,
        Select_range: `The number of joins that used ranges on the first table.`,
        Select_range_check: `The number of joins without keys that check for key usage after each row.If this is not 0, you should carefully check the indexes of your tables.`,
        Select_scan: `The number of joins that did a full scan of the first table.`,
        Slave_heartbeat_period: `Shows the replication heartbeat interval(in seconds) on a replication replica.`,
        Slave_last_heartbeat: `Shows when the most recent heartbeat signal was received by a replica, as a TIMESTAMP value.`,
        Slave_open_temp_tables: `The number of temporary tables that the replica SQL thread currently has open.`,
        Slave_received_heartbeats: `This counter increments with each replication heartbeat received by a replication replica since the last time.`,
        Slave_retried_transactions: `The total number of times since startup that the replication replica SQL thread has retried transactions.`,
        Slave_rows_last_search_algorithm_used: `The search algorithm that was most recently used by this replica to locate rows for row - based replication.`,
        Slave_running: `This is ON if this server is a replica that is connected to a replication source, and both the I / O and SQL threads are running; otherwise, it is OFF.`,
        Slow_queries: `The number of queries that have taken more than long_query_time seconds.`,
        Sort_merge_passes: `The number of merge passes that the sort algorithm has had to do.`,
        Sort_range: `The number of sorts that were done using ranges.`,
        Sort_rows: `The number of sorted rows.`,
        Sort_scan: `The number of sorts that were done by scanning the table.`,
        Ssl_accept_renegotiates: `The number of negotiates needed to establish the connection.`,
        Ssl_accepts: `The number of accepted SSL connections.`,
        Ssl_callback_cache_hits: `The number of callback cache hits.`,
        Ssl_cipher: `The current encryption cipher(empty for unencrypted connections).`,
        Ssl_cipher_list: `The list of possible SSL ciphers(empty for non - SSL connections).`,
        Ssl_client_connects: `The number of SSL connection attempts to an SSL - enabled source.`,
        Ssl_connect_renegotiates: `The number of negotiates needed to establish the connection to an SSL - enabled source.`,
        Ssl_ctx_verify_depth: `The SSL context verification depth.`,
        Ssl_ctx_verify_mode: `The SSL context verification mode.`,
        Ssl_default_timeout: `The default SSL timeout.`,
        Ssl_finished_accepts: `The number of successful SSL connections to the server.`,
        Ssl_finished_connects: `The number of successful replica connections to an SSL - enabled source.`,
        Ssl_server_not_after: `The last date for which the SSL certificate is valid.`,
        Ssl_server_not_before: `The first date for which the SSL certificate is valid.`,
        Ssl_session_cache_hits: `The number of SSL session cache hits.`,
        Ssl_session_cache_misses: `The number of SSL session cache misses.`,
        Ssl_session_cache_mode: `The SSL session cache mode.`,
        Ssl_session_cache_overflows: `The number of SSL session cache overflows.`,
        Ssl_session_cache_size: `The SSL session cache size.`,
        Ssl_session_cache_timeouts: `The number of SSL session cache timeouts.`,
        Ssl_sessions_reused: `How many SSL connections were reused from the cache.`,
        Ssl_used_session_cache_entries: `How many SSL session cache entries were used.`,
        Ssl_verify_depth: `The verification depth for replication SSL connections.`,
        Ssl_verify_mode: `The verification mode used by the server for a connection that uses SSL.`,
        SSL_VERIFY_PEER: `indicates that the server asks for a client certificate.`,
        SSL_VERIFY_CLIENT_ONCE: `indicates that a request for the client certificate is done only in the initial handshake.`,
        Ssl_version: `The SSL protocol version of the connection.`,
        Table_locks_immediate: `The number of times that a request for a table lock could be granted immediately.`,
        Table_locks_waited: `The number of times that a request for a table lock could not be granted immediately and a wait was needed.`,
        Table_open_cache_hits: `The number of hits for open tables cache lookups.`,
        Table_open_cache_misses: `The number of misses for open tables cache lookups.`,
        Table_open_cache_overflows: `The number of overflows for the open tables cache.`,
        Tc_log_max_pages_used: `the largest number of pages used for the log since the server started.`,
        Tc_log_page_size: `The page size used for the memory.`,
        Tc_log_page_waits: `this variable increments each time the server was not able to commit a transaction and had to wait for a free page in the log.`,
        Threads_cached: `The number of threads in the thread cache.`,
        Threads_connected: `The number of currently open connections.`,
        Threads_created: `The number of threads created to handle connections.`,
        Threads_running: `The number of threads that are not sleeping.`,
        Uptime: `The number of seconds that the server has been up.`,
        Uptime_since_flush_status: `The number of seconds since the most recent FLUSH STATUS statement.`
    }
}